# Generated by Django 4.2.3 on 2023-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='aucktion',
            new_name='auction',
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisements',
        ),
    ]
